### ISSUE TITLE
ruby 1.9 encoding fix

### ISSUE THREAD

**Issue by sunaku** [belen-albeza/space-shooter-gosu#1]
I use ruby 1.9.1p378 (2010-01-10 revision 26273) [i686-linux] and get this error:

<pre>
/home/sun/lab/space-shooter/engine.rb:4:in `require': /home/sun/lab/space-shooter/engine/credits_state.rb:20: invalid multibyte char (US-ASCII) (SyntaxError)
/home/sun/lab/space-shooter/engine/credits_state.rb:20: invalid multibyte char (US-ASCII)
/home/sun/lab/space-shooter/engine/credits_state.rb:20: syntax error, unexpected $end, expecting ')'
...  @font_credits.draw_rel("Belén Albeza", Game::ScreenWidth ...
...                               ^
    from /home/sun/lab/space-shooter/engine.rb:4:in `<top (required)>'
    from main.rb:4:in `require'
    from main.rb:4:in `<main>'
</pre>

This can be fixed by adding this line at the top of engine/credits_state.rb:

<pre>
# encoding: utf-8
</pre>

Cheers.

**Comment by sunaku** [comment]
Commit dc3609ef534ef9aabe853a2bd7f34b785fdd74dd seems to have fixed this issue.  Closing.
